name: Node.js Server
on:
  repository_dispatch:
    types: [register, unregister]

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: node index.js
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          SECURITY_KEY: ${{ secrets.SECURITY_KEY }}
